apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 --file docker-compose.yml convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: w3c-report-em-tool
  name: w3c-report-em-tool
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: w3c-report-em-tool
    spec:
      containers:
      - image: w3c-report-em-tool
        name: w3c-report-em-tool
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
status: {}
