apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 --file docker-compose.yml convert
      -c
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: w3c-report-em-tool
  name: w3c-report-em-tool
spec:
  ports:
  - name: "8089"
    port: 8089
    targetPort: 9000
  selector:
    io.kompose.service: w3c-report-em-tool
status:
  loadBalancer: {}
